# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocaine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default='Enter Text Here'),
            preserve_default=False,
        ),
    ]
