# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cocaine', '0002_experience_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='addeddate',
            new_name='Start_Date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='datesfrom',
        ),
        migrations.AddField(
            model_name='experience',
            name='End_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='Published_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
