# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cocaine', '0003_auto_20160613_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 6, 14, 14, 16, 20, 786091, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
